#!/usr/bin/env python3
"""CLIAnything for router-ai-atius.

Operational CLI for the live Podman deployment. It intentionally avoids
application secrets in normal output and uses dry-run by default for writes.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import json
import os
import re
import shutil
import subprocess
import sys
import textwrap
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable


DB_BACKEND = os.environ.get("CLIANYTHING_DB_BACKEND", "host").lower()
DB_CONTAINER = os.environ.get("CLIANYTHING_DB_CONTAINER", "postgres")
DB_NAME = os.environ.get("CLIANYTHING_DB_NAME", "DBRouterAiAtius" if DB_BACKEND == "host" else "DBRouterAiAtius")
DB_USER = os.environ.get("CLIANYTHING_DB_USER", "admin")
HOST_PSQL_SUDO_USER = os.environ.get("CLIANYTHING_HOST_PSQL_SUDO_USER", "postgres")
POD_NAME = os.environ.get("CLIANYTHING_POD_NAME", "atius-ai-router")
DEFAULT_BASE_URL = os.environ.get("CLIANYTHING_BASE_URL", "http://127.0.0.1:3000")
REPO_ROOT = Path(os.environ.get("CLIANYTHING_ROOT", "/home/ubuntu/GitHub/containers/router-ai-atius"))
BACKUP_ROOT = Path(os.environ.get("CLIANYTHING_BACKUP_ROOT", str(REPO_ROOT / "backups" / "clianything")))
MANAGEMENT_DOCS_ROOT = REPO_ROOT / "docs" / "atius-router-docs" / "content" / "docs" / "en" / "api" / "management"
ENDPOINTS_MANIFEST = REPO_ROOT / "tools" / "clianything_endpoints.json"
ENDPOINT_CLASSIFICATIONS = {"db-crud", "api-action", "read-only", "auth-flow", "external-webhook", "unsupported-safe"}
MUTATING_METHODS = {"POST", "PUT", "PATCH", "DELETE"}
PROVIDER_CONSOLIDATION_MINIMAX_MODELS = ("MiniMax-M3", "MiniMax-M2.7", "MiniMax-M2.5-highspeed", "MiniMax-M2.5", "embo-01")
PROVIDER_CONSOLIDATION_DEEPSEEK_MODELS = ("deepseek-v4-pro", "deepseek-v4-flash")
PHASE19_MINIMAX_EMBEDDING_TYPES = {"query", "db"}
LEGACY_SPLIT_CHANNEL_NAMES = {
    "MiniMax - OpenAI-Compatible",
    "MiniMax - Anthropic-Compatible",
    "MiniMax - Embeddings",
    "DeepSeek - OpenAI-Compatible",
    "DeepSeek - Anthropic-Compatible",
    "OpenAI - Embeddings",
    "Codex - Embeddings",
}


@dataclass(frozen=True)
class Resource:
    table: str
    label: str
    area: str
    description: str


RESOURCES: dict[str, Resource] = {
    "abilities": Resource("abilities", "abilities", "routing", "Model-to-channel routing weights, priorities and groups."),
    "channels": Resource("channels", "channels", "routing", "Provider channels: type, base_url, models, keys and routing settings."),
    "models": Resource("models", "models", "catalog", "Admin model catalog shown in the frontend."),
    "vendors": Resource("vendors", "vendors", "catalog", "Model vendor records used by the catalog."),
    "options": Resource("options", "options", "settings", "System settings and frontend console options."),
    "users": Resource("users", "users", "identity", "User accounts, roles, quotas and profile fields."),
    "tokens": Resource("tokens", "tokens", "identity", "API tokens generated by users/admins."),
    "logs": Resource("logs", "logs", "observability", "Usage logs and request accounting rows."),
    "usage_tracking": Resource("usage_tracking", "usage-tracking", "observability", "Aggregated usage tracking records."),
    "perf_metrics": Resource("perf_metrics", "perf-metrics", "observability", "Model/channel performance metrics buckets."),
    "quota_data": Resource("quota_data", "quota-data", "observability", "Quota aggregation rows by user/model/time."),
    "tasks": Resource("tasks", "tasks", "jobs", "Async task records for image/video/other job platforms."),
    "midjourneys": Resource("midjourneys", "midjourneys", "jobs", "Legacy Midjourney-style drawing/video task records."),
    "redemptions": Resource("redemptions", "redemptions", "billing", "Redeem code records."),
    "top_ups": Resource("top_ups", "top-ups", "billing", "Wallet top-up/payment records."),
    "subscription_plans": Resource("subscription_plans", "subscription-plans", "billing", "Subscription plan definitions."),
    "subscription_orders": Resource("subscription_orders", "subscription-orders", "billing", "Subscription purchase orders."),
    "user_subscriptions": Resource("user_subscriptions", "user-subscriptions", "billing", "Active and historical user subscriptions."),
    "subscription_pre_consume_records": Resource(
        "subscription_pre_consume_records",
        "subscription-pre-consume-records",
        "billing",
        "Pre-consumption accounting records for subscriptions.",
    ),
    "prefill_groups": Resource("prefill_groups", "prefill-groups", "groups", "Group presets used by admin group screens."),
    "checkins": Resource("checkins", "checkins", "engagement", "Daily check-in quota awards."),
    "custom_oauth_providers": Resource("custom_oauth_providers", "custom-oauth-providers", "identity", "Custom OAuth/OIDC provider configs."),
    "user_oauth_bindings": Resource("user_oauth_bindings", "user-oauth-bindings", "identity", "User to OAuth provider bindings."),
    "two_fas": Resource("two_fas", "two-fas", "security", "Two-factor auth secrets/status by user."),
    "two_fa_backup_codes": Resource("two_fa_backup_codes", "two-fa-backup-codes", "security", "2FA backup code hashes."),
    "passkey_credentials": Resource("passkey_credentials", "passkey-credentials", "security", "WebAuthn/passkey credentials."),
    "setups": Resource("setups", "setups", "system", "Setup/migration initialization state."),
}

ALIASES = {
    "group": "prefill_groups",
    "groups": "prefill_groups",
    "channel": "channels",
    "provider": "channels",
    "providers": "channels",
    "model": "models",
    "token": "tokens",
    "user": "users",
    "log": "logs",
    "redemption": "redemptions",
    "oauth": "custom_oauth_providers",
    "oauth-providers": "custom_oauth_providers",
    "subscriptions": "user_subscriptions",
    "plans": "subscription_plans",
    "orders": "subscription_orders",
    "tasks-log": "tasks",
}

SENSITIVE_NAME_RE = re.compile(
    r"(password|passwd|secret|token|api[_-]?key|access[_-]?key|refresh|credential|private|session|cookie|"
    r"authorization|code_hash|client_secret|dsn|key$|^key$)",
    re.IGNORECASE,
)
SENSITIVE_COLUMNS = {
    "key",
    "value",
    "password",
    "access_token",
    "client_secret",
    "secret",
    "code_hash",
    "credential_id",
    "public_key",
    "private_data",
    "header_override",
    "param_override",
    "other",
    "other_info",
    "settings",
    "setting",
    "channel_info",
    "provider_payload",
}


class CliError(RuntimeError):
    pass


class StrictStatusError(CliError):
    pass


def run(cmd: list[str], *, input_text: str | None = None, check: bool = True) -> subprocess.CompletedProcess[str]:
    try:
        proc = subprocess.run(
            cmd,
            input=input_text,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
    except FileNotFoundError as exc:
        raise CliError(f"Comando nao encontrado: {cmd[0]}") from exc
    if check and proc.returncode != 0:
        detail = proc.stderr.strip() or proc.stdout.strip()
        raise CliError(f"Falha ao executar {' '.join(cmd[:4])}: {detail}")
    return proc


def psql_base_cmd(binary: str) -> list[str]:
    if DB_BACKEND == "podman":
        return ["podman", "exec", "-i", DB_CONTAINER, binary, "-U", DB_USER, "-d", DB_NAME]
    if DB_BACKEND == "host":
        prefix = ["sudo", "-u", HOST_PSQL_SUDO_USER] if HOST_PSQL_SUDO_USER else []
        return [*prefix, binary, "-d", DB_NAME]
    raise CliError("CLIANYTHING_DB_BACKEND invalido: use 'host' ou 'podman'")


def run_psql(sql: str, *, raw: bool = False) -> str:
    cmd = [
        *psql_base_cmd("psql"),
        "-X",
        "-q",
        "-v",
        "ON_ERROR_STOP=1",
        "-t",
        "-A",
        "-c",
        sql,
    ]
    out = run(cmd).stdout
    return out if raw else out.strip()


def run_psql_json(select_sql: str) -> list[dict[str, Any]]:
    sql = f"select coalesce(jsonb_agg(to_jsonb(q)), '[]'::jsonb)::text from ({select_sql}) q"
    out = run_psql(sql)
    if not out:
        return []
    try:
        payload = json.loads(out)
    except json.JSONDecodeError as exc:
        raise CliError(f"Resposta JSON invalida do psql: {out[:200]}") from exc
    if not isinstance(payload, list):
        raise CliError("Resposta JSON inesperada do psql.")
    return payload


def run_psql_json_dml(dml_sql: str) -> list[dict[str, Any]]:
    sql = f"with mutated as ({dml_sql}) select coalesce(jsonb_agg(to_jsonb(mutated)), '[]'::jsonb)::text from mutated"
    out = run_psql(sql)
    if not out:
        return []
    try:
        payload = json.loads(out)
    except json.JSONDecodeError as exc:
        raise CliError(f"Resposta JSON invalida do psql: {out[:200]}") from exc
    if not isinstance(payload, list):
        raise CliError("Resposta JSON inesperada do psql.")
    return payload


def quote_ident(name: str) -> str:
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
        raise CliError(f"Identificador invalido: {name}")
    return '"' + name.replace('"', '""') + '"'


def sql_literal(value: str) -> str:
    lowered = value.lower()
    if lowered == "null":
        return "NULL"
    if lowered in {"true", "false"}:
        return "TRUE" if lowered == "true" else "FALSE"
    if re.fullmatch(r"-?\d+(\.\d+)?", value):
        return value
    if value.startswith("@"):
        path = Path(value[1:]).expanduser()
        if not path.exists():
            raise CliError(f"Arquivo para valor @ nao encontrado: {path}")
        value = path.read_text(encoding="utf-8")
    return "'" + value.replace("'", "''") + "'"


def is_legacy_split_channel(name: str, base_url: str) -> bool:
    normalized_name = name.strip()
    normalized_base_url = base_url.strip().lower().rstrip("/")
    if normalized_name in LEGACY_SPLIT_CHANNEL_NAMES:
        return True
    if normalized_name.startswith(("MiniMax - ", "DeepSeek - ")) and (
        normalized_name.endswith("-Compatible") or normalized_name.endswith("- Embeddings")
    ):
        return True
    return normalized_base_url in {
        "https://api.minimax.io/anthropic",
        "https://api.deepseek.com/anthropic",
    }


def normalize_resource(name: str) -> Resource:
    key = ALIASES.get(name, name).replace("-", "_")
    key = ALIASES.get(key, key)
    if key not in RESOURCES:
        known = ", ".join(sorted(RESOURCES))
        raise CliError(f"Recurso desconhecido: {name}. Use um destes: {known}")
    return RESOURCES[key]


def schema_for(resource: Resource) -> list[dict[str, Any]]:
    table = resource.table
    sql = f"""
        select column_name, data_type, is_nullable, column_default
        from information_schema.columns
        where table_schema = 'public' and table_name = {sql_literal(table)}
        order by ordinal_position
    """
    rows = run_psql_json(sql)
    if not rows:
        raise CliError(f"Tabela nao encontrada no banco: {table}")
    return rows


def column_names(resource: Resource) -> set[str]:
    return {row["column_name"] for row in schema_for(resource)}


def validate_columns(resource: Resource, cols: Iterable[str]) -> None:
    known = column_names(resource)
    bad = [col for col in cols if col not in known]
    if bad:
        raise CliError(f"Colunas invalidas para {resource.table}: {', '.join(bad)}")


def parse_key_values(values: list[str]) -> dict[str, str]:
    parsed: dict[str, str] = {}
    for item in values:
        if "=" not in item:
            raise CliError(f"Use chave=valor: {item}")
        key, value = item.split("=", 1)
        if not key:
            raise CliError(f"Chave vazia em: {item}")
        parsed[key] = value
    return parsed


def build_where(resource: Resource, args: argparse.Namespace) -> str:
    filters = parse_key_values(getattr(args, "filter", []) or [])
    if getattr(args, "id", None) is not None:
        filters["id"] = str(args.id)
    if not filters:
        return ""
    validate_columns(resource, filters.keys())
    parts = [f"{quote_ident(key)} = {sql_literal(value)}" for key, value in filters.items()]
    return " where " + " and ".join(parts)


def parse_order(resource: Resource, order: str | None) -> str:
    cols = column_names(resource)
    if not order:
        return ' order by "id" desc' if "id" in cols else ""
    raw_col, _, raw_dir = order.partition(":")
    direction = raw_dir.lower() or "asc"
    if raw_col not in cols:
        raise CliError(f"Coluna de ordenacao invalida para {resource.table}: {raw_col}")
    if direction not in {"asc", "desc"}:
        raise CliError("Direcao de ordenacao deve ser asc ou desc.")
    return f" order by {quote_ident(raw_col)} {direction}"


def redact_value(column: str, value: Any, row: dict[str, Any] | None = None) -> Any:
    if value in (None, ""):
        return value
    lower = column.lower()
    row_key = str((row or {}).get("key", "")).lower()
    if lower in SENSITIVE_COLUMNS or SENSITIVE_NAME_RE.search(lower):
        return "<redacted>"
    if lower == "value" and SENSITIVE_NAME_RE.search(row_key):
        return "<redacted>"
    return value


def redact_rows(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    redacted = []
    for row in rows:
        redacted.append({key: redact_value(key, value, row) for key, value in row.items()})
    return redacted


def format_scalar(value: Any, *, max_len: int = 120) -> str:
    if value is None:
        text = ""
    elif isinstance(value, (dict, list)):
        text = json.dumps(value, ensure_ascii=False, separators=(",", ":"))
    else:
        text = str(value)
    text = text.replace("\n", "\\n")
    if len(text) > max_len:
        return text[: max_len - 3] + "..."
    return text


def print_table(rows: list[dict[str, Any]]) -> None:
    if not rows:
        print("[]")
        return
    columns = list(rows[0].keys())
    widths: dict[str, int] = {}
    for col in columns:
        widths[col] = min(max(len(col), *(len(format_scalar(row.get(col), max_len=80)) for row in rows)), 80)
    header = "  ".join(col.ljust(widths[col]) for col in columns)
    print(header)
    print("  ".join("-" * widths[col] for col in columns))
    for row in rows:
        print("  ".join(format_scalar(row.get(col), max_len=80).ljust(widths[col]) for col in columns))


def emit(rows: list[dict[str, Any]], fmt: str) -> None:
    rows = redact_rows(rows)
    if fmt == "json":
        print(json.dumps(rows, ensure_ascii=False, indent=2, sort_keys=True))
        return
    if fmt == "csv":
        if not rows:
            return
        writer = csv.DictWriter(sys.stdout, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
        return
    print_table(rows)


def backup_table(resource: Resource) -> Path:
    BACKUP_ROOT.mkdir(parents=True, exist_ok=True)
    stamp = dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    path = BACKUP_ROOT / f"{stamp}_{resource.table}.sql"
    cmd = [
        *psql_base_cmd("pg_dump"),
        "--data-only",
        "--column-inserts",
        "-t",
        f"public.{resource.table}",
    ]
    proc = run(cmd)
    path.write_text(proc.stdout, encoding="utf-8")
    return path


def build_redacted_write_preview(sql: str) -> str:
    return textwrap.dedent(sql).strip()


def write_channel_from_source_key(
    *,
    source_id: int,
    name: str,
    type_value: int | str,
    base_url: str,
    models: str,
    group: str = "default",
    priority: int = 0,
    weight: int = 0,
    status: int = 1,
    remark: str | None = None,
) -> str:
    """Build a secret-safe INSERT...SELECT that reuses the source channel key."""
    remark_sql = "NULL" if remark in (None, "") else sql_literal(remark)
    return textwrap.dedent(
        f"""
        insert into channels (
          key, open_ai_organization, test_model, status, name, weight,
          created_time, test_time, response_time, base_url, other, balance,
          balance_updated_time, models, "group", used_quota, model_mapping,
          status_code_mapping, priority, auto_ban, other_info, tag, setting,
          param_override, header_override, remark, channel_info, settings, type
        )
        select
          c.key,
          c.open_ai_organization,
          c.test_model,
          {sql_literal(str(status))},
          {sql_literal(name)},
          {sql_literal(str(weight))},
          c.created_time,
          c.test_time,
          c.response_time,
          {sql_literal(base_url)},
          c.other,
          c.balance,
          c.balance_updated_time,
          {sql_literal(models)},
          {sql_literal(group)},
          c.used_quota,
          c.model_mapping,
          c.status_code_mapping,
          {sql_literal(str(priority))},
          c.auto_ban,
          c.other_info,
          c.tag,
          c.setting,
          c.param_override,
          c.header_override,
          {remark_sql},
          c.channel_info,
          c.settings,
          {sql_literal(str(type_value))}
        from channels c
        where c.id = {sql_literal(str(source_id))}
        returning *
        """
    ).strip()


def build_channel_insert_sql(
    *,
    name: str,
    type_value: int | str,
    base_url: str,
    models: str,
    key: str,
    group: str = "default",
    priority: int = 0,
    weight: int = 0,
    status: int = 1,
    remark: str | None = None,
) -> str:
    remark_sql = "NULL" if remark in (None, "") else sql_literal(remark)
    return textwrap.dedent(
        f"""
        insert into channels (
          key, status, name, weight, base_url, models, "group",
          priority, remark, type
        )
        values (
          {sql_literal(key)},
          {sql_literal(str(status))},
          {sql_literal(name)},
          {sql_literal(str(weight))},
          {sql_literal(base_url)},
          {sql_literal(models)},
          {sql_literal(group)},
          {sql_literal(str(priority))},
          {remark_sql},
          {sql_literal(str(type_value))}
        )
        returning *
        """
    ).strip()


def build_phase19_provider_actions(openai_api_key: str | None = None) -> list[tuple[Resource, str, str]]:
    _ = openai_api_key
    actions: list[tuple[Resource, str, str]] = []
    channel_resource = normalize_resource("channels")
    abilities_resource = normalize_resource("abilities")

    rename_codex_sql = textwrap.dedent(
        """
        update channels
        set name = 'OpenAI - Codex'
        where id = 5
        returning *
        """
    ).strip()
    actions.append((channel_resource, rename_codex_sql, "rename Codex channel -> OpenAI - Codex"))

    minimax_channel_sql = textwrap.dedent(
        """
        update channels
        set
          status = 1,
          name = 'MiniMax',
          weight = 0,
          base_url = 'https://api.minimax.io',
          models = 'MiniMax-M3,MiniMax-M2.7,MiniMax-M2.5-highspeed,MiniMax-M2.5,embo-01',
          "group" = 'default',
          priority = 0,
          param_override = '',
          remark = '2026-06-18: unified MiniMax OpenAI/Anthropic/Embeddings routing in Go; replaces channels 3 and 6 as active routes.',
          type = 35
        where id = 1
        returning *
        """
    ).strip()
    actions.append((channel_resource, minimax_channel_sql, "consolidate MiniMax channel"))

    deepseek_channel_sql = textwrap.dedent(
        """
        update channels
        set
          status = 1,
          name = 'DeepSeek',
          weight = 0,
          base_url = 'https://api.deepseek.com',
          models = 'deepseek-v4-pro,deepseek-v4-flash',
          "group" = 'default',
          priority = 0,
          remark = '2026-06-18: unified DeepSeek OpenAI/Anthropic routing in Go; replaces channel 7 as active route.',
          type = 43
        where id = 2
        returning *
        """
    ).strip()
    actions.append((channel_resource, deepseek_channel_sql, "consolidate DeepSeek channel"))

    minimax_abilities_sql = textwrap.dedent(
        f"""
        insert into abilities ("group", model, channel_id, enabled, priority, weight, tag)
        select
          'default',
          model_name,
          1,
          true,
          0,
          0,
          null
        from (values {", ".join(f"('{model}')" for model in PROVIDER_CONSOLIDATION_MINIMAX_MODELS)}) as m(model_name)
        on conflict ("group", model, channel_id) do update
        set enabled = excluded.enabled,
            priority = excluded.priority,
            weight = excluded.weight,
            tag = excluded.tag
        returning *
        """
    ).strip()
    actions.append((abilities_resource, minimax_abilities_sql, "add consolidated MiniMax abilities"))

    deepseek_abilities_sql = textwrap.dedent(
        f"""
        insert into abilities ("group", model, channel_id, enabled, priority, weight, tag)
        select
          'default',
          model_name,
          2,
          true,
          0,
          0,
          null
        from (values {", ".join(f"('{model}')" for model in PROVIDER_CONSOLIDATION_DEEPSEEK_MODELS)}) as m(model_name)
        on conflict ("group", model, channel_id) do update
        set enabled = excluded.enabled,
            priority = excluded.priority,
            weight = excluded.weight,
            tag = excluded.tag
        returning *
        """
    ).strip()
    actions.append((abilities_resource, deepseek_abilities_sql, "add consolidated DeepSeek abilities"))

    disable_channels_sql = textwrap.dedent(
        """
        update channels
        set
          status = 2,
          remark = '2026-06-18: disabled after Go-native provider consolidation; route through MiniMax, DeepSeek, or OpenAI - Codex.'
        where id in (3, 6, 7, 8)
        returning *
        """
    ).strip()
    actions.append((channel_resource, disable_channels_sql, "disable merged provider channels"))

    disable_abilities_sql = textwrap.dedent(
        """
        update abilities
        set enabled = false
        where channel_id in (3, 6, 7, 8)
        returning *
        """
    ).strip()
    actions.append((abilities_resource, disable_abilities_sql, "disable merged provider abilities"))

    return actions


def run_sql_actions(args: argparse.Namespace, actions: list[tuple[Resource, str, str]]) -> None:
    resources: list[Resource] = []
    for resource, _sql, _label in actions:
        if resource not in resources:
            resources.append(resource)

    if not getattr(args, "execute", False):
        for _resource, sql, label in actions:
            print(f"# {label}")
            print(build_redacted_write_preview(sql))
            print()
        print("DRY-RUN: nada foi alterado. Adicione --execute para aplicar.")
        return

    backups = [backup_table(resource) for resource in resources]
    for path in backups:
        print(f"Backup antes da escrita: {path}")

    for _resource, sql, label in actions:
        run_psql(sql)
        print(f"Applied: {label}")


def require_podman() -> None:
    if shutil.which("podman") is None:
        raise CliError("podman nao esta no PATH.")


def cmd_resources(_args: argparse.Namespace) -> None:
    rows = [
        {
            "resource": name,
            "table": res.table,
            "area": res.area,
            "description": res.description,
        }
        for name, res in sorted(RESOURCES.items())
    ]
    print_table(rows)


def cmd_schema(args: argparse.Namespace) -> None:
    resource = normalize_resource(args.resource)
    emit(schema_for(resource), args.format)


def cmd_list(args: argparse.Namespace) -> None:
    resource = normalize_resource(args.resource)
    validate_columns(resource, [item.split("=", 1)[0] for item in args.filter or []])
    where = build_where(resource, args)
    order = parse_order(resource, args.order)
    limit = max(1, min(args.limit, 5000))
    offset = max(0, args.offset)
    sql = f"select * from {quote_ident(resource.table)}{where}{order} limit {limit} offset {offset}"
    emit(run_psql_json(sql), args.format)


def cmd_get(args: argparse.Namespace) -> None:
    resource = normalize_resource(args.resource)
    where = build_where(resource, args)
    if not where:
        raise CliError("Use --id ou --filter para selecionar o registro.")
    sql = f"select * from {quote_ident(resource.table)}{where} limit 20"
    emit(run_psql_json(sql), args.format)


def cmd_export(args: argparse.Namespace) -> None:
    resource = normalize_resource(args.resource)
    where = build_where(resource, args)
    order = parse_order(resource, args.order)
    limit_sql = "" if args.limit == 0 else f" limit {max(1, min(args.limit, 100000))}"
    sql = f"select * from {quote_ident(resource.table)}{where}{order}{limit_sql}"
    emit(run_psql_json(sql), args.format)


def dryrun_or_execute(args: argparse.Namespace, resource: Resource, sql: str) -> None:
    print(sql)
    if not args.execute:
        print("\nDRY-RUN: nada foi alterado. Adicione --execute para aplicar.")
        return
    backup = backup_table(resource)
    print(f"Backup antes da escrita: {backup}")
    run_psql(sql)
    print("Applied.")


def cmd_create(args: argparse.Namespace) -> None:
    resource = normalize_resource(args.resource)
    values = parse_key_values(args.set or [])
    if not values:
        raise CliError("Use pelo menos um --set coluna=valor.")
    validate_columns(resource, values.keys())
    cols = ", ".join(quote_ident(col) for col in values)
    vals = ", ".join(sql_literal(val) for val in values.values())
    sql = f"insert into {quote_ident(resource.table)} ({cols}) values ({vals}) returning *"
    dryrun_or_execute(args, resource, sql)


def cmd_update(args: argparse.Namespace) -> None:
    resource = normalize_resource(args.resource)
    values = parse_key_values(args.set or [])
    if not values:
        raise CliError("Use pelo menos um --set coluna=valor.")
    validate_columns(resource, values.keys())
    where = build_where(resource, args)
    if not where:
        raise CliError("Update exige --id ou --filter.")
    sets = ", ".join(f"{quote_ident(col)} = {sql_literal(val)}" for col, val in values.items())
    sql = f"update {quote_ident(resource.table)} set {sets}{where} returning *"
    dryrun_or_execute(args, resource, sql)


def cmd_delete(args: argparse.Namespace) -> None:
    resource = normalize_resource(args.resource)
    where = build_where(resource, args)
    if not where:
        raise CliError("Delete exige --id ou --filter.")
    sql = f"delete from {quote_ident(resource.table)}{where} returning *"
    dryrun_or_execute(args, resource, sql)


def cmd_backup(args: argparse.Namespace) -> None:
    resource = normalize_resource(args.resource)
    path = backup_table(resource)
    print(path)


def ensure_read_only(sql: str) -> None:
    cleaned = re.sub(r"/\*.*?\*/", " ", sql, flags=re.S)
    cleaned = re.sub(r"--.*?$", " ", cleaned, flags=re.M).strip().lower()
    if not cleaned.startswith(("select", "with", "show", "explain")):
        raise CliError("query aceita apenas SQL read-only: select/with/show/explain.")
    blocked = re.search(
        r"\b(insert|update|delete|drop|alter|truncate|create|grant|revoke|copy|call|do|vacuum|reindex)\b",
        cleaned,
    )
    if blocked:
        raise CliError(f"SQL bloqueado em modo read-only: {blocked.group(1)}")


def cmd_query(args: argparse.Namespace) -> None:
    ensure_read_only(args.sql)
    sql = args.sql.rstrip(";")
    if args.format == "raw":
        print(run_psql(sql, raw=True))
        return
    emit(run_psql_json(sql), args.format)


def http_json(url: str, timeout: float = 5.0) -> tuple[int | str, Any]:
    try:
        with urllib.request.urlopen(url, timeout=timeout) as resp:
            body = resp.read().decode("utf-8", errors="replace")
            code: int | str = resp.status
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        code = exc.code
    except Exception as exc:  # noqa: BLE001 - CLI diagnostic output should include the failure.
        return "error", str(exc)
    try:
        return code, json.loads(body)
    except json.JSONDecodeError:
        return code, body[:400]


def cmd_status(args: argparse.Namespace) -> None:
    require_podman()
    rows: list[dict[str, Any]] = []
    pod = run(["podman", "pod", "inspect", POD_NAME, "--format", "{{.State}}\t{{.NumContainers}}"], check=False)
    rows.append(
        {
            "check": "pod",
            "target": POD_NAME,
            "status": "ok" if pod.returncode == 0 else "fail",
            "detail": pod.stdout.strip() or pod.stderr.strip(),
        }
    )
    ps = run(
        ["podman", "ps", "--filter", f"pod={POD_NAME}", "--format", "{{.Names}}\t{{.Status}}\t{{.Ports}}"],
        check=False,
    )
    rows.append(
        {
            "check": "containers",
            "target": POD_NAME,
            "status": "ok" if ps.returncode == 0 and ps.stdout.strip() else "fail",
            "detail": ps.stdout.strip().replace("\n", " | ")[:500] or ps.stderr.strip(),
        }
    )
    for label, url in [
        ("backend", f"{DEFAULT_BASE_URL}/api/status"),
        ("v1-models", f"{DEFAULT_BASE_URL}/v1/models"),
    ]:
        code, payload = http_json(url)
        status = "fail"
        if label == "v1-models" and code == 401:
            status = "ok"
        elif code == 200:
            status = "ok"
        rows.append({"check": "http", "target": label, "status": status, "detail": f"{code} {format_scalar(payload)}"})
    count_sql = """
        select 'channels' as item, count(*) as count from channels
        union all select 'models', count(*) from models
        union all select 'tokens', count(*) from tokens
        union all select 'users', count(*) from users
        union all select 'logs', count(*) from logs
    """
    try:
        db_rows = run_psql_json(count_sql)
        rows.append({"check": "db", "target": DB_NAME, "status": "ok", "detail": format_scalar(db_rows)})
    except Exception as exc:  # noqa: BLE001
        rows.append({"check": "db", "target": DB_NAME, "status": "fail", "detail": str(exc)})
    print_table(rows)
    if getattr(args, "strict", False):
        bad = [row for row in rows if row["status"] != "ok"]
        if bad:
            summary = ", ".join(f"{row['target']}={row['status']}" for row in bad)
            raise StrictStatusError(f"status --strict encontrou componentes nao-ok: {summary}")


def cmd_providers(args: argparse.Namespace) -> None:
    sql = """
        select
          c.id,
          c.name,
          c.type,
          c.status,
          c.priority,
          c.weight,
          c."group",
          c.base_url,
          c.models,
          coalesce(a.enabled_count, 0) as enabled_abilities,
          coalesce(a.total_count, 0) as total_abilities
        from channels c
        left join (
          select channel_id,
                 count(*) filter (where enabled) as enabled_count,
                 count(*) as total_count
          from abilities
          group by channel_id
        ) a on a.channel_id = c.id
    """
    if not args.all:
        sql += " where c.status = 1"
    sql += " order by c.status desc, c.priority asc nulls last, c.id asc"
    emit(run_psql_json(sql), args.format)


def build_embeddings_overview_sql() -> str:
    return """
        select
          c.id as channel_id,
          c.name as channel_name,
          c.status,
          c.type,
          c.base_url,
          c.models,
          coalesce(a.enabled_count, 0) as enabled_abilities,
          coalesce(a.total_count, 0) as total_abilities
        from channels c
        left join (
          select
            channel_id,
            count(*) filter (where enabled) as enabled_count,
            count(*) as total_count
          from abilities
          where model in (
            'embo-01',
            'text-embedding-3-small',
            'text-embedding-3-large',
            'embedding-gte-v1'
          )
          group by channel_id
        ) a on a.channel_id = c.id
        where c.name like '%Embeddings%'
           or c.models ilike '%embo-01%'
           or c.models ilike '%text-embedding-3%'
           or c.models ilike '%embedding-gte-v1%'
        order by c.status desc, c.id asc
    """


def cmd_embeddings(args: argparse.Namespace) -> None:
    emit(run_psql_json(build_embeddings_overview_sql()), args.format)


def cmd_models(args: argparse.Namespace) -> None:
    if args.from_channels:
        sql = """
            select id as channel_id, name as channel_name, status, models
            from channels
            where models is not null and models <> ''
            order by status desc, id asc
        """
    else:
        sql = "select * from models order by status desc, id asc"
    emit(run_psql_json(sql), args.format)


def cmd_codex_catalog(args: argparse.Namespace) -> None:
    if args.channel_id < 1:
        raise CliError("--channel-id deve ser positivo.")
    headers = list(args.header)
    user_id = args.user_id
    if user_id is None:
        raw_user_id = os.environ.get("ATIUS_ROUTER_ADMIN_USER_ID", "").strip()
        if raw_user_id:
            try:
                user_id = int(raw_user_id)
            except ValueError as exc:
                raise CliError("ATIUS_ROUTER_ADMIN_USER_ID deve ser inteiro positivo.") from exc
    if user_id is not None:
        if user_id < 1:
            raise CliError("--user-id deve ser positivo.")
        headers.append(f"New-Api-User: {user_id}")
    has_user_header = any(header.partition(":")[0].strip().lower() == "new-api-user" for header in headers)
    if args.execute and not has_user_header:
        raise CliError("Informe --user-id ou ATIUS_ROUTER_ADMIN_USER_ID para autenticacao root.")
    request_api(
        method="POST",
        path="/api/option/codex_catalog/sync",
        base_url=args.base_url,
        data=json.dumps({"channel_id": args.channel_id}),
        bearer=args.bearer,
        headers_extra=headers,
        timeout=args.timeout,
        execute=args.execute,
    )


def cmd_logs(args: argparse.Namespace) -> None:
    limit = max(1, min(args.limit, 500))
    sql = f"""
        select id, created_at, user_id, username, token_name, model_name, quota,
               prompt_tokens, completion_tokens, use_time, channel_id, channel_name,
               request_id, upstream_request_id
        from logs
        order by id desc
        limit {limit}
    """
    emit(run_psql_json(sql), args.format)


def load_api_body(raw: str | None) -> bytes | None:
    if raw is None:
        return None
    if raw.startswith("@"):
        return Path(raw[1:]).expanduser().read_bytes()
    return raw.encode("utf-8")


def request_api(
    *,
    method: str,
    path: str,
    base_url: str,
    data: str | None,
    bearer: str | None,
    headers_extra: list[str],
    timeout: float,
    execute: bool,
    require_execute: bool = False,
) -> None:
    base = base_url.rstrip("/")
    path = path if path.startswith("/") else "/" + path
    url = base + path
    headers = {"Accept": "application/json"}
    if data is not None:
        headers["Content-Type"] = "application/json"
    bearer = bearer or os.environ.get("ATIUS_ROUTER_ADMIN_TOKEN")
    if bearer:
        headers["Authorization"] = f"Bearer {bearer}"
    for item in headers_extra or []:
        if ":" not in item:
            raise CliError(f"Header invalido, use Nome: valor: {item}")
        key, value = item.split(":", 1)
        headers[key.strip()] = value.strip()
    method = method.upper()
    if (method in MUTATING_METHODS or require_execute) and not execute:
        print(f"DRY-RUN API: {method} {url}")
        if data:
            print(redact_text(data) if not data.startswith("@") else f"body={data} (conteudo nao exibido)")
        print("Nada foi enviado. Adicione --execute para aplicar.")
        return
    req = urllib.request.Request(url, data=load_api_body(data), method=method, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            code = resp.status
            body = resp.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as exc:
        code = exc.code
        body = exc.read().decode("utf-8", errors="replace")
    try:
        payload = json.loads(body)
        print(json.dumps(redact_json(payload), ensure_ascii=False, indent=2, sort_keys=True))
    except json.JSONDecodeError:
        print(redact_text(body))
    print(f"\nHTTP {code}", file=sys.stderr)


def cmd_api(args: argparse.Namespace) -> None:
    entry = find_manifest_entry_for_request(args.method, args.path)
    request_api(
        method=args.method,
        path=args.path,
        base_url=args.base_url,
        data=args.data,
        bearer=args.bearer,
        headers_extra=args.header,
        timeout=args.timeout,
        execute=args.execute,
        require_execute=endpoint_requires_execute(entry) if entry else False,
    )


def endpoint_requires_execute(entry: dict[str, Any]) -> bool:
    classification = str(entry.get("classification", ""))
    method = str(entry.get("method", "")).upper()
    return method in MUTATING_METHODS or classification in {"api-action", "auth-flow", "external-webhook"}


def endpoint_template_matches(template: str, request_path: str) -> bool:
    if template == request_path:
        return True
    pattern = re.escape(template)
    pattern = re.sub(r"\\\{[^/{}]+\\\}", r"[^/]+", pattern)
    return re.fullmatch(pattern, request_path) is not None


def find_manifest_entry_for_request(method: str, path: str) -> dict[str, Any] | None:
    method = method.upper()
    normalized = path if path.startswith("/") else "/" + path
    request_path = urllib.parse.urlsplit(normalized).path or "/"
    entries = load_endpoint_manifest()
    exact = manifest_by_key(entries).get(endpoint_key(method, request_path))
    if exact:
        return exact
    for entry in entries:
        if str(entry.get("method", "")).upper() != method:
            continue
        if endpoint_template_matches(str(entry.get("path", "")), request_path):
            return entry
    return None


def get_manifest_entry(method: str, path: str) -> dict[str, Any]:
    key = endpoint_key(method, path)
    entry = manifest_by_key(load_endpoint_manifest()).get(key)
    if not entry:
        raise CliError(f"Endpoint nao mapeado no manifesto: {key}. Use coverage --strict para diagnosticar.")
    return entry


def build_endpoint_path(template: str, params: list[str] | None = None, query: list[str] | None = None) -> str:
    path = template
    for key, value in parse_key_values(params or []).items():
        path = path.replace("{" + key + "}", urllib.parse.quote(str(value), safe=""))
    missing = re.findall(r"\{([^}]+)\}", path)
    if missing:
        raise CliError(f"Parametros obrigatorios ausentes para path: {', '.join(sorted(set(missing)))}")
    query_values = parse_key_values(query or [])
    if query_values:
        path += ("&" if "?" in path else "?") + urllib.parse.urlencode(query_values)
    return path


def invoke_manifest_endpoint(
    args: argparse.Namespace,
    method: str,
    path_template: str,
    *,
    params: list[str] | None = None,
    query: list[str] | None = None,
    data: str | None = None,
) -> None:
    entry = get_manifest_entry(method, path_template)
    if entry["classification"] == "unsupported-safe":
        raise CliError(f"Endpoint classificado como unsupported-safe: {method.upper()} {path_template}")
    path = build_endpoint_path(path_template, params=params, query=query)
    request_api(
        method=method,
        path=path,
        base_url=args.base_url,
        data=data,
        bearer=args.bearer,
        headers_extra=args.header,
        timeout=args.timeout,
        execute=getattr(args, "execute", False),
        require_execute=endpoint_requires_execute(entry),
    )


def cmd_endpoint_list(args: argparse.Namespace) -> None:
    entries = load_endpoint_manifest()
    rows = []
    for entry in entries:
        if args.group and entry["group"] != args.group:
            continue
        if args.classification and entry["classification"] != args.classification:
            continue
        rows.append(
            {
                "method": entry["method"],
                "path": entry["path"],
                "group": entry["group"],
                "classification": entry["classification"],
                "safe_default": entry["safe_default"],
                "cli_command": entry["cli_command"],
            }
        )
    emit(rows, args.format)


def cmd_endpoint_show(args: argparse.Namespace) -> None:
    entry = get_manifest_entry(args.method, args.path)
    print(json.dumps(entry, ensure_ascii=False, indent=2, sort_keys=True))


def cmd_endpoint_invoke(args: argparse.Namespace) -> None:
    invoke_manifest_endpoint(
        args,
        args.method,
        args.path,
        params=args.param,
        query=args.query,
        data=args.data,
    )


def cmd_channel(args: argparse.Namespace) -> None:
    action = args.channel_action
    if action in {"enable", "disable"}:
        resource = normalize_resource("channels")
        status = "1" if action == "enable" else "2"
        sql = f"update channels set status = {status} where id = {sql_literal(str(args.id))} returning *"
        dryrun_or_execute(args, resource, sql)
        return
    if action == "test":
        invoke_manifest_endpoint(args, "GET", "/api/channel/test/{id}", params=[f"id={args.id}"])
        return
    if action == "fetch-models":
        invoke_manifest_endpoint(args, "GET", "/api/channel/fetch_models/{id}", params=[f"id={args.id}"])
        return
    if action == "balance":
        path = "/api/channel/update_balance/{id}" if args.id is not None else "/api/channel/update_balance"
        params = [f"id={args.id}"] if args.id is not None else []
        invoke_manifest_endpoint(args, "GET", path, params=params)
        return
    if action == "copy":
        invoke_manifest_endpoint(args, "POST", "/api/channel/copy/{id}", params=[f"id={args.id}"])
        return
    if action == "models":
        invoke_manifest_endpoint(args, "GET", "/api/channel/models")
        return
    if action == "models-enabled":
        invoke_manifest_endpoint(args, "GET", "/api/channel/models_enabled")
        return
    if action == "search":
        invoke_manifest_endpoint(args, "GET", "/api/channel/search", query=[f"keyword={args.keyword}"])
        return
    if action == "clone-keyed":
        if is_legacy_split_channel(args.name, args.base_url) and not args.allow_legacy_split:
            raise CliError(
                "clone-keyed bloqueou um canal legado separado. Use canais unificados MiniMax/DeepSeek/OpenAI - Codex "
                "ou informe --allow-legacy-split para uma acao manual excepcional."
            )
        sql = write_channel_from_source_key(
            source_id=args.source_id,
            name=args.name,
            type_value=args.type,
            base_url=args.base_url,
            models=args.models,
            group=args.group,
            priority=args.priority,
            weight=args.weight,
            status=args.status,
            remark=args.remark,
        )
        resource = normalize_resource("channels")
        if not args.execute:
            print(build_redacted_write_preview(sql))
            print("\nDRY-RUN: nada foi alterado. Adicione --execute para aplicar.")
            return
        backup = backup_table(resource)
        print(f"Backup antes da escrita: {backup}")
        run_psql(sql)
        print("Applied: clone-keyed")
        return
    if action == "phase19-apply":
        actions = build_phase19_provider_actions()
        run_sql_actions(args, actions)
        return
    raise CliError(f"Acao de channel desconhecida: {action}")


def cmd_model_api(args: argparse.Namespace) -> None:
    if args.model_action == "missing":
        invoke_manifest_endpoint(args, "GET", "/api/models/missing")
        return
    if args.model_action == "sync-upstream":
        if args.preview:
            invoke_manifest_endpoint(args, "GET", "/api/models/sync_upstream/preview")
        else:
            invoke_manifest_endpoint(args, "POST", "/api/models/sync_upstream")
        return
    raise CliError(f"Acao de model desconhecida: {args.model_action}")


def cmd_option(args: argparse.Namespace) -> None:
    if args.option_action == "get":
        where = f" where key = {sql_literal(args.key)}" if args.key else ""
        emit(run_psql_json(f"select key, value from options{where} order by key asc"), args.format)
        return
    if args.option_action == "set":
        resource = normalize_resource("options")
        sql = (
            "insert into options (key, value) "
            f"values ({sql_literal(args.key)}, {sql_literal(args.value)}) "
            "on conflict (key) do update set value = excluded.value returning *"
        )
        dryrun_or_execute(args, resource, sql)
        return
    raise CliError(f"Acao de option desconhecida: {args.option_action}")


def cmd_ratio(args: argparse.Namespace) -> None:
    if args.ratio_action == "channels":
        invoke_manifest_endpoint(args, "GET", "/api/ratio_sync/channels")
        return
    if args.ratio_action == "fetch":
        invoke_manifest_endpoint(args, "POST", "/api/ratio_sync/fetch")
        return
    if args.ratio_action == "reset":
        invoke_manifest_endpoint(args, "POST", "/api/option/rest_model_ratio")
        return
    raise CliError(f"Acao de ratio desconhecida: {args.ratio_action}")


def cmd_token_api(args: argparse.Namespace) -> None:
    if args.token_action == "usage":
        invoke_manifest_endpoint(args, "GET", "/api/usage/token/")
        return
    raise CliError(f"Acao de token desconhecida: {args.token_action}")


def cmd_log_api(args: argparse.Namespace) -> None:
    if args.log_action == "stat":
        invoke_manifest_endpoint(args, "GET", "/api/log/stat")
        return
    if args.log_action == "delete":
        if not args.confirm_delete_all:
            raise CliError("log delete exige --confirm-delete-all alem de --execute.")
        invoke_manifest_endpoint(args, "DELETE", "/api/log/")
        return
    raise CliError(f"Acao de log desconhecida: {args.log_action}")


def cmd_task_api(args: argparse.Namespace) -> None:
    paths = {
        "list": "/api/task/",
        "self": "/api/task/self",
        "mj": "/api/mj/",
        "mj-self": "/api/mj/self",
    }
    invoke_manifest_endpoint(args, "GET", paths[args.task_action])


def cmd_vendor_api(args: argparse.Namespace) -> None:
    if args.vendor_action == "search":
        invoke_manifest_endpoint(args, "GET", "/api/vendors/search", query=[f"keyword={args.keyword}"])
        return
    raise CliError(f"Acao de vendor desconhecida: {args.vendor_action}")


def redact_json(value: Any, key: str = "") -> Any:
    if isinstance(value, dict):
        return {k: redact_json(v, k) for k, v in value.items()}
    if isinstance(value, list):
        return [redact_json(item, key) for item in value]
    return redact_value(key, value)


def redact_text(value: str) -> str:
    patterns = [
        (r"Bearer\s+[A-Za-z0-9._~+/=-]+", "Bearer <redacted>"),
        (r"sk-[A-Za-z0-9]{10,}", "sk-redacted"),
        (r"(?i)(password|passwd|secret|token|api[_-]?key|authorization)(['\"\s:=]+)([^,'\"\s}]+)", r"\1\2<redacted>"),
    ]
    text = value
    for pattern, repl in patterns:
        text = re.sub(pattern, repl, text)
    return text


def endpoint_key(method: str, path: str) -> str:
    return f"{method.upper()} {path}"


def parse_management_docs(root: Path = MANAGEMENT_DOCS_ROOT) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    endpoints: list[dict[str, Any]] = []
    docs_without_operations: list[dict[str, Any]] = []
    if not root.exists():
        raise CliError(f"Diretorio de docs management nao encontrado: {root}")
    for file_path in sorted(root.rglob("*.mdx")):
        rel = file_path.relative_to(root).as_posix()
        group = rel.split("/", 1)[0] if "/" in rel else rel.replace(".mdx", "")
        text = file_path.read_text(encoding="utf-8")
        matches = re.findall(r'\{"path":"([^"]+)","method":"([^"]+)"\}', text)
        if not matches:
            docs_without_operations.append({"group": group, "doc": rel})
            continue
        for path, method in matches:
            endpoints.append({"group": group, "doc": rel, "method": method.upper(), "path": path})
    return endpoints, docs_without_operations


def load_endpoint_manifest(path: Path = ENDPOINTS_MANIFEST) -> list[dict[str, Any]]:
    if not path.exists():
        raise CliError(f"Manifesto de endpoints nao encontrado: {path}")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise CliError(f"Manifesto de endpoints JSON invalido: {path}") from exc
    if not isinstance(payload, list):
        raise CliError("Manifesto de endpoints deve ser uma lista JSON.")
    return payload


def validate_endpoint_manifest(entries: list[dict[str, Any]]) -> list[str]:
    problems: list[str] = []
    required = {"group", "name", "method", "path", "doc", "classification", "cli_command", "safe_default", "requires_auth", "notes"}
    seen: set[str] = set()
    for index, entry in enumerate(entries):
        missing = sorted(required - set(entry))
        if missing:
            problems.append(f"entry[{index}] faltando campos: {', '.join(missing)}")
        method = str(entry.get("method", "")).upper()
        path = str(entry.get("path", ""))
        key = endpoint_key(method, path)
        if key in seen:
            problems.append(f"endpoint duplicado no manifesto: {key}")
        seen.add(key)
        classification = entry.get("classification")
        if classification not in ENDPOINT_CLASSIFICATIONS:
            problems.append(f"{key}: classification invalida: {classification}")
        cli_command = str(entry.get("cli_command", "")).strip()
        if classification == "api-action" and (not cli_command or cli_command.startswith("clianything api")):
            problems.append(f"{key}: api-action exige cli_command tipado")
        if cli_command.startswith("clianything api"):
            problems.append(f"{key}: wrapper generico nao conta como paridade")
        if entry.get("requires_auth") not in {True, False}:
            problems.append(f"{key}: requires_auth deve ser boolean")
    return problems


def manifest_by_key(entries: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {endpoint_key(str(entry["method"]), str(entry["path"])): entry for entry in entries}


def render_coverage_payload() -> dict[str, Any]:
    docs, docs_without_operations = parse_management_docs()
    manifest = load_endpoint_manifest()
    problems = validate_endpoint_manifest(manifest)
    docs_map = manifest_by_key(docs)
    manifest_map = manifest_by_key(manifest)
    missing_from_manifest = [
        {**entry, "key": endpoint_key(str(entry["method"]), str(entry["path"]))}
        for key, entry in docs_map.items()
        if key not in manifest_map
    ]
    extra_in_manifest = [
        {**entry, "key": endpoint_key(str(entry["method"]), str(entry["path"]))}
        for key, entry in manifest_map.items()
        if key not in docs_map
    ]

    groups: dict[str, dict[str, Any]] = {}
    for entry in manifest:
        group = str(entry["group"])
        classification = str(entry["classification"])
        bucket = groups.setdefault(
            group,
            {
                "group": group,
                "total": 0,
                "db_crud": 0,
                "api_action": 0,
                "read_only": 0,
                "auth_flow": 0,
                "external_webhook": 0,
                "unsupported_safe": 0,
                "direct_cli": 0,
            },
        )
        bucket["total"] += 1
        bucket[classification.replace("-", "_")] += 1
        if not str(entry.get("cli_command", "")).startswith("clianything endpoint invoke"):
            bucket["direct_cli"] += 1

    total_docs = len(docs)
    total_manifest = len(manifest)
    covered = total_docs - len(missing_from_manifest)
    return {
        "summary": {
            "docs_endpoints": total_docs,
            "manifest_endpoints": total_manifest,
            "covered_endpoints": covered,
            "coverage_percent": round((covered / total_docs) * 100, 2) if total_docs else 0.0,
            "groups": len(groups),
            "docs_without_operations": len(docs_without_operations),
            "problems": len(problems),
            "missing_from_manifest": len(missing_from_manifest),
            "extra_in_manifest": len(extra_in_manifest),
        },
        "groups": [groups[key] for key in sorted(groups)],
        "docs_without_operations": docs_without_operations,
        "problems": problems,
        "missing_from_manifest": missing_from_manifest,
        "extra_in_manifest": extra_in_manifest,
        "endpoints": sorted(manifest, key=lambda item: (str(item["group"]), str(item["path"]), str(item["method"]))),
    }


def cmd_coverage(args: argparse.Namespace) -> None:
    payload = render_coverage_payload()
    if args.format == "json":
        print(json.dumps(payload if args.details else {k: payload[k] for k in ("summary", "groups", "problems", "missing_from_manifest", "extra_in_manifest", "docs_without_operations")}, ensure_ascii=False, indent=2, sort_keys=True))
    elif args.format == "csv":
        writer = csv.DictWriter(sys.stdout, fieldnames=list(payload["groups"][0].keys()) if payload["groups"] else ["group"])
        writer.writeheader()
        writer.writerows(payload["groups"])
    else:
        print_table(payload["groups"])
        summary = payload["summary"]
        print(
            "\n"
            f"coverage={summary['coverage_percent']}% "
            f"docs={summary['docs_endpoints']} manifest={summary['manifest_endpoints']} "
            f"missing={summary['missing_from_manifest']} extra={summary['extra_in_manifest']} "
            f"problems={summary['problems']} docs_without_operations={summary['docs_without_operations']}"
        )
        if args.details:
            print("\nEndpoints:")
            print_table(
                [
                    {
                        "method": item["method"],
                        "path": item["path"],
                        "classification": item["classification"],
                        "cli_command": item["cli_command"],
                    }
                    for item in payload["endpoints"]
                ]
            )
        if payload["problems"]:
            print("\nProblems:")
            for problem in payload["problems"]:
                print(f"- {problem}")
        if payload["missing_from_manifest"]:
            print("\nMissing from manifest:")
            for entry in payload["missing_from_manifest"]:
                print(f"- {entry['key']} ({entry['doc']})")
        if payload["extra_in_manifest"]:
            print("\nExtra in manifest:")
            for entry in payload["extra_in_manifest"]:
                print(f"- {entry['key']} ({entry['doc']})")
    if args.strict and (
        payload["problems"] or payload["missing_from_manifest"] or payload["extra_in_manifest"]
    ):
        raise CliError("coverage strict falhou: corrija manifesto/cobertura antes de prosseguir.")

def cmd_call(args: argparse.Namespace) -> None:
    entries = load_endpoint_manifest()
    target = args.name_or_endpoint
    match = None
    for entry in entries:
        key = endpoint_key(str(entry["method"]), str(entry["path"]))
        if target in {str(entry["name"]), key, str(entry["path"])}:
            match = entry
            break
    if match is None:
        raise CliError(f"Endpoint nao encontrado no manifesto: {target}")
    if match["classification"] in {"auth-flow", "external-webhook", "unsupported-safe"}:
        raise CliError(f"Endpoint classificado como {match['classification']} nao deve ser chamado por CLI generico.")

    path = str(match["path"])
    for item in args.param or []:
        if "=" not in item:
            raise CliError(f"Parametro invalido, use nome=valor: {item}")
        key, value = item.split("=", 1)
        path = path.replace("{" + key + "}", urllib.parse.quote(value, safe=""))
    if re.search(r"\{[^}]+\}", path):
        raise CliError(f"Faltam parametros de path para: {path}")
    request_api(
        method=str(match["method"]),
        path=path,
        base_url=args.base_url,
        data=args.data,
        bearer=args.bearer,
        headers_extra=args.header,
        timeout=args.timeout,
        execute=args.execute,
        require_execute=endpoint_requires_execute(match),
    )


def add_common_format(parser: argparse.ArgumentParser, *, raw: bool = False) -> None:
    choices = ["table", "json", "csv"]
    if raw:
        choices.append("raw")
    parser.add_argument("--format", choices=choices, default="table")


def add_api_transport_args(parser: argparse.ArgumentParser, *, data: bool = False, execute: bool = True) -> None:
    if data:
        parser.add_argument("--data", help="JSON literal ou @arquivo.")
    parser.add_argument("--header", action="append", default=[], help="Header no formato Nome: valor.")
    parser.add_argument("--bearer", help="Bearer token. Tambem aceita env ATIUS_ROUTER_ADMIN_TOKEN.")
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL)
    parser.add_argument("--timeout", type=float, default=15.0)
    if execute:
        parser.add_argument("--execute", action="store_true", help="Executa chamada potencialmente mutante; sem isso fica em dry-run.")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="clianything",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="Gerencia o router-ai-atius por CLI: DB, providers, modelos, logs e API local.",
        epilog=textwrap.dedent(
            """
            Exemplos:
              clianything status
              clianything providers
              clianything embeddings
              clianything list channels --limit 10
              clianything get channels --id 3 --format json
              clianything update channels --id 3 --set status=1
              clianything update channels --id 3 --set status=1 --execute
              clianything api GET /api/status
            """
        ),
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("status", help="Mostra saude do pod, HTTP e DB.")
    p.add_argument("--strict", action="store_true", help="Retorna erro se algum componente estiver degraded/fail.")
    p.set_defaults(func=cmd_status)

    p = sub.add_parser("coverage", help="Compara endpoints management com manifesto de paridade CLI.")
    p.add_argument("--strict", action="store_true", help="Falha se existir endpoint sem cobertura/classificacao valida.")
    p.add_argument("--details", action="store_true", help="Mostra cada endpoint mapeado.")
    add_common_format(p)
    p.set_defaults(func=cmd_coverage)

    p = sub.add_parser("resources", help="Lista recursos cobertos pelo CLI.")
    p.set_defaults(func=cmd_resources)

    p = sub.add_parser("schema", help="Mostra schema de um recurso.")
    p.add_argument("resource")
    add_common_format(p)
    p.set_defaults(func=cmd_schema)

    p = sub.add_parser("list", help="Lista registros de um recurso.")
    p.add_argument("resource")
    p.add_argument("--limit", type=int, default=50)
    p.add_argument("--offset", type=int, default=0)
    p.add_argument("--filter", action="append", default=[], help="Filtro exato coluna=valor. Pode repetir.")
    p.add_argument("--order", help="Ordenacao coluna[:asc|desc]. Padrao: id:desc quando existir.")
    add_common_format(p)
    p.set_defaults(func=cmd_list)

    p = sub.add_parser("get", help="Busca registros por id ou filtro exato.")
    p.add_argument("resource")
    p.add_argument("--id", type=int)
    p.add_argument("--filter", action="append", default=[], help="Filtro exato coluna=valor. Pode repetir.")
    add_common_format(p)
    p.set_defaults(func=cmd_get)

    p = sub.add_parser("export", help="Exporta recurso em JSON ou CSV.")
    p.add_argument("resource")
    p.add_argument("--limit", type=int, default=0, help="0 exporta tudo.")
    p.add_argument("--filter", action="append", default=[])
    p.add_argument("--order")
    add_common_format(p)
    p.set_defaults(func=cmd_export)

    p = sub.add_parser("create", help="Cria registro. Dry-run por padrao.")
    p.add_argument("resource")
    p.add_argument("--set", action="append", default=[], required=True, help="coluna=valor. Pode repetir.")
    p.add_argument("--execute", action="store_true", help="Aplica a escrita e faz backup antes.")
    add_common_format(p)
    p.set_defaults(func=cmd_create)

    p = sub.add_parser("update", help="Atualiza registro. Dry-run por padrao.")
    p.add_argument("resource")
    p.add_argument("--id", type=int)
    p.add_argument("--filter", action="append", default=[])
    p.add_argument("--set", action="append", default=[], required=True, help="coluna=valor. Pode repetir.")
    p.add_argument("--execute", action="store_true", help="Aplica a escrita e faz backup antes.")
    add_common_format(p)
    p.set_defaults(func=cmd_update)

    p = sub.add_parser("delete", help="Remove registro. Dry-run por padrao.")
    p.add_argument("resource")
    p.add_argument("--id", type=int)
    p.add_argument("--filter", action="append", default=[])
    p.add_argument("--execute", action="store_true", help="Aplica a escrita e faz backup antes.")
    add_common_format(p)
    p.set_defaults(func=cmd_delete)

    p = sub.add_parser("backup", help="Faz pg_dump data-only de um recurso.")
    p.add_argument("resource")
    p.set_defaults(func=cmd_backup)

    p = sub.add_parser("query", help="Executa SQL read-only.")
    p.add_argument("sql")
    add_common_format(p, raw=True)
    p.set_defaults(func=cmd_query)

    p = sub.add_parser("providers", help="Resumo dos providers/channels e routing abilities.")
    p.add_argument("--all", action="store_true", help="Inclui channels desabilitados.")
    add_common_format(p)
    p.set_defaults(func=cmd_providers)

    p = sub.add_parser("embeddings", help="Resumo dos providers de embeddings e seus statuses.")
    add_common_format(p)
    p.set_defaults(func=cmd_embeddings)

    p = sub.add_parser("models", help="Lista catalogo de modelos ou modelos declarados em channels.")
    p.add_argument("--from-channels", action="store_true")
    add_common_format(p)
    p.set_defaults(func=cmd_models)

    p_codex_catalog = sub.add_parser("codex-catalog", help="Operacoes root do catalogo Codex.")
    codex_catalog_sub = p_codex_catalog.add_subparsers(dest="codex_catalog_action", required=True)
    p = codex_catalog_sub.add_parser("sync", help="Executa discovery, validacao e promocao do catalogo Codex.")
    p.add_argument("--channel-id", type=int, default=5)
    p.add_argument("--user-id", type=int, help="ID do usuario root; tambem aceita env ATIUS_ROUTER_ADMIN_USER_ID.")
    add_api_transport_args(p)
    p.set_defaults(func=cmd_codex_catalog, timeout=330.0)

    p = sub.add_parser("logs", help="Atalho para ultimos usage logs sem campos sensiveis.")
    p.add_argument("--limit", type=int, default=20)
    add_common_format(p)
    p.set_defaults(func=cmd_logs)

    p_endpoint = sub.add_parser("endpoint", help="Lista, mostra ou invoca endpoints mapeados no manifesto.")
    endpoint_sub = p_endpoint.add_subparsers(dest="endpoint_action", required=True)
    p = endpoint_sub.add_parser("list", help="Lista endpoints de management mapeados.")
    p.add_argument("--group")
    p.add_argument("--classification", choices=sorted(ENDPOINT_CLASSIFICATIONS))
    add_common_format(p)
    p.set_defaults(func=cmd_endpoint_list)
    p = endpoint_sub.add_parser("show", help="Mostra um endpoint do manifesto.")
    p.add_argument("method")
    p.add_argument("path")
    p.set_defaults(func=cmd_endpoint_show)
    p = endpoint_sub.add_parser("invoke", help="Invoca endpoint mapeado com dry-run seguro.")
    p.add_argument("method")
    p.add_argument("path")
    p.add_argument("--param", action="append", default=[], help="Parametro path chave=valor, ex.: id=3.")
    p.add_argument("--query", action="append", default=[], help="Query string chave=valor. Pode repetir.")
    add_api_transport_args(p, data=True)
    p.set_defaults(func=cmd_endpoint_invoke)

    p_channel = sub.add_parser("channel", help="Operacoes frontend/CLI para providers/channels.")
    channel_sub = p_channel.add_subparsers(dest="channel_action", required=True)
    for name, help_text in [
        ("test", "Testa um channel especifico."),
        ("fetch-models", "Busca modelos declarados pelo provider."),
        ("copy", "Copia um channel existente."),
    ]:
        p = channel_sub.add_parser(name, help=help_text)
        p.add_argument("--id", type=int, required=True)
        add_api_transport_args(p)
        p.set_defaults(func=cmd_channel)
    p = channel_sub.add_parser("clone-keyed", help="Clona um channel usando a key do source sem exibir segredo.")
    p.add_argument("--source-id", type=int, required=True)
    p.add_argument("--name", required=True)
    p.add_argument("--type", required=True)
    p.add_argument("--base-url", required=True)
    p.add_argument("--models", required=True)
    p.add_argument("--group", default="default")
    p.add_argument("--priority", type=int, default=0)
    p.add_argument("--weight", type=int, default=0)
    p.add_argument("--status", type=int, default=2, help="Status inicial; default 2 deixa o clone desabilitado.")
    p.add_argument("--remark")
    p.add_argument("--allow-legacy-split", action="store_true", help="Permite criar canal legado separado em caso excepcional.")
    p.add_argument("--execute", action="store_true", help="Aplica a escrita e faz backup antes.")
    add_common_format(p)
    p.set_defaults(func=cmd_channel)
    p = channel_sub.add_parser("balance", help="Atualiza saldo de um channel ou de todos.")
    p.add_argument("--id", type=int)
    add_api_transport_args(p)
    p.set_defaults(func=cmd_channel)
    for name, help_text in [("enable", "Habilita channel via DB."), ("disable", "Desabilita channel via DB.")]:
        p = channel_sub.add_parser(name, help=help_text)
        p.add_argument("--id", type=int, required=True)
        p.add_argument("--execute", action="store_true", help="Aplica a escrita e faz backup antes.")
        add_common_format(p)
        p.set_defaults(func=cmd_channel)
    p = channel_sub.add_parser("models", help="Lista modelos disponiveis nos channels pela API.")
    add_api_transport_args(p, execute=False)
    p.set_defaults(func=cmd_channel)
    p = channel_sub.add_parser("models-enabled", help="Lista modelos habilitados nos channels pela API.")
    add_api_transport_args(p, execute=False)
    p.set_defaults(func=cmd_channel)
    p = channel_sub.add_parser("search", help="Busca channels pela API.")
    p.add_argument("keyword")
    add_api_transport_args(p, execute=False)
    p.set_defaults(func=cmd_channel)
    p = channel_sub.add_parser(
        "phase19-apply",
        help="Aplica o estado consolidado Go-native de providers/embeddings (compat legado Phase 19).",
    )
    p.add_argument("--execute", action="store_true", help="Aplica a escrita e faz backup antes.")
    add_common_format(p)
    p.set_defaults(func=cmd_channel)

    p_model = sub.add_parser("model", help="Operacoes frontend/CLI para catalogo de modelos.")
    model_sub = p_model.add_subparsers(dest="model_action", required=True)
    p = model_sub.add_parser("missing", help="Lista modelos ausentes.")
    add_api_transport_args(p, execute=False)
    p.set_defaults(func=cmd_model_api)
    p = model_sub.add_parser("sync-upstream", help="Sincroniza modelos upstream; use --preview para nao alterar.")
    p.add_argument("--preview", action="store_true")
    add_api_transport_args(p)
    p.set_defaults(func=cmd_model_api)

    p_option = sub.add_parser("option", help="Le ou altera system options.")
    option_sub = p_option.add_subparsers(dest="option_action", required=True)
    p = option_sub.add_parser("get", help="Le options; opcionalmente uma chave.")
    p.add_argument("key", nargs="?")
    add_common_format(p)
    p.set_defaults(func=cmd_option)
    p = option_sub.add_parser("set", help="Altera option via DB. Dry-run por padrao.")
    p.add_argument("key")
    p.add_argument("value")
    p.add_argument("--execute", action="store_true", help="Aplica a escrita e faz backup antes.")
    add_common_format(p)
    p.set_defaults(func=cmd_option)

    p_ratio = sub.add_parser("ratio", help="Operacoes de model ratio sync.")
    ratio_sub = p_ratio.add_subparsers(dest="ratio_action", required=True)
    p = ratio_sub.add_parser("channels", help="Lista channels para ratio sync.")
    add_api_transport_args(p, execute=False)
    p.set_defaults(func=cmd_ratio)
    for name, help_text in [("fetch", "Busca ratio upstream."), ("reset", "Reseta model ratio.")]:
        p = ratio_sub.add_parser(name, help=help_text)
        add_api_transport_args(p)
        p.set_defaults(func=cmd_ratio)

    p_token = sub.add_parser("token", help="Operacoes de token management alem do CRUD DB.")
    token_sub = p_token.add_subparsers(dest="token_action", required=True)
    p = token_sub.add_parser("usage", help="Mostra uso de tokens pela API.")
    add_api_transport_args(p, execute=False)
    p.set_defaults(func=cmd_token_api)

    p_log = sub.add_parser("log", help="Operacoes API de logs.")
    log_sub = p_log.add_subparsers(dest="log_action", required=True)
    p = log_sub.add_parser("stat", help="Mostra estatisticas de logs pela API.")
    add_api_transport_args(p, execute=False)
    p.set_defaults(func=cmd_log_api)
    p = log_sub.add_parser("delete", help="Remove logs pela API com confirmacao dupla.")
    p.add_argument("--confirm-delete-all", action="store_true")
    add_api_transport_args(p)
    p.set_defaults(func=cmd_log_api)

    p_task = sub.add_parser("task", help="Lista tasks/MJ pela API.")
    task_sub = p_task.add_subparsers(dest="task_action", required=True)
    for name, help_text in [
        ("list", "Lista tasks."),
        ("self", "Lista tasks do usuario atual."),
        ("mj", "Lista registros MJ."),
        ("mj-self", "Lista registros MJ do usuario atual."),
    ]:
        p = task_sub.add_parser(name, help=help_text)
        add_api_transport_args(p, execute=False)
        p.set_defaults(func=cmd_task_api)

    p_vendor = sub.add_parser("vendor", help="Operacoes API de vendors.")
    vendor_sub = p_vendor.add_subparsers(dest="vendor_action", required=True)
    p = vendor_sub.add_parser("search", help="Busca vendors pela API.")
    p.add_argument("keyword")
    add_api_transport_args(p, execute=False)
    p.set_defaults(func=cmd_vendor_api)

    p = sub.add_parser("api", help="Chamada generica para a API local do router.")
    p.add_argument("method", choices=["GET", "POST", "PUT", "PATCH", "DELETE", "get", "post", "put", "patch", "delete"])
    p.add_argument("path")
    p.add_argument("--data", help="JSON literal ou @arquivo.")
    p.add_argument("--header", action="append", default=[], help="Header no formato Nome: valor.")
    p.add_argument("--bearer", help="Bearer token. Tambem aceita env ATIUS_ROUTER_ADMIN_TOKEN.")
    p.add_argument("--base-url", default=DEFAULT_BASE_URL)
    p.add_argument("--timeout", type=float, default=15.0)
    p.add_argument("--execute", action="store_true", help="Obrigatorio para POST/PUT/PATCH/DELETE.")
    p.set_defaults(func=cmd_api)

    p = sub.add_parser("call", help="Chama endpoint pelo nome do manifesto com guards de escrita.")
    p.add_argument("name_or_endpoint", help="Nome do manifesto, 'METHOD /path' ou path exato.")
    p.add_argument("--param", action="append", default=[], help="Parametro de path nome=valor. Pode repetir.")
    p.add_argument("--data", help="JSON literal ou @arquivo.")
    p.add_argument("--header", action="append", default=[], help="Header no formato Nome: valor.")
    p.add_argument("--bearer", help="Bearer token. Tambem aceita env ATIUS_ROUTER_ADMIN_TOKEN.")
    p.add_argument("--base-url", default=DEFAULT_BASE_URL)
    p.add_argument("--timeout", type=float, default=15.0)
    p.add_argument("--execute", action="store_true", help="Obrigatorio para POST/PUT/PATCH/DELETE.")
    p.set_defaults(func=cmd_call)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        args.func(args)
    except CliError as exc:
        print(f"erro: {exc}", file=sys.stderr)
        return 2
    except KeyboardInterrupt:
        print("interrompido", file=sys.stderr)
        return 130
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
